# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven and Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK and Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Run unit tests
      - name: Unit Test
        run: mvn -B test --file pom.xml

      # Build with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Build Docker image
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: yaredgidey/githubtest:latest, yaredgidey/githubtest:${{github.run_number}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push Docker image to Docker Hub
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: yaredgidey/githubtest:latest, yaredgidey/githubtest:${{github.run_number}}

      # Clone deployment repository
      - name: Checkout deployment repository
        uses: actions/checkout@v3
        with:
          repository:  yaredgh/githubActionTest-deployment-
          ref: main
      - name: Get directory
        run: |
          ls 
          cd githubActionTest-deployment
          ls

      # Update deployment YAML
      - name: Update deployment YAML
        run: |
          touch yared.txt
          #sed -i "s|image: old_image|image: yaredgidey/githubtest:${{github.run_number}}|g" githubActionTest-deployment/deployment.yaml
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add deployment.yaml
          git commit -m "Update deployment.yaml with new image tag"
          git push origin main

#      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#       - name: Update dependency graph
#         uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#            context:
#            push: true
#            tags: yaredgidey/app:latest, yaredgidey/app:${{github.run_number}}
#    - name: Build and Push Docker Image
#      uses: mr-smithers-excellent/docker-build-push@v4
#      with:
#          image: yaredgidey/githubtest
#          registry: docker.io
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
